backend:
  name: github
  repo: civilservicelgbt/civilservicelgbt.github.io
  branch: main # Branch to update
publish_mode: editorial_workflow
media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }