backend:
  name: 'github'
  repo: 'civilservicelgbt/civilservicelgbt.github.io'
  branch: 'main' # Branch to update
  api_root: 'https://api.github.com'
  site_domain: 'civilservicelgbt.netlify.app'
  base_url: 'https://api.netlify.com'
  auth_endpoint: 'auth'
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "Upload “{{path}}”"
    deleteMedia: "Delete “{{path}}”"
    openAuthoring: "'{{message}}'"

publish_mode: editorial_workflow

show_preview_links: true

site_url: 'https://www.civilservice.lgbt'
logo_url: 'https://www.civilservice.lgbt/assets/images/site/cms-icon.svg'

media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: 'news'
    label: 'News article'
    folder: '_news/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: 'news/{{year}}/{{month}}/{{day}}/{{slug}}'
    preview_path_date_field: date
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'news' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Publish date', name: 'date', widget: 'datetime' , date_format: "YYYY-MM-DD", time_format: "HH:mm" }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'list', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Featured image', name: 'image', widget: 'image', choose_url: true, required: false }
      - { label: 'YouTube video URL', name: 'video', widget: 'string', required: false }
      - { label: 'Redirect from', name: 'redirect_from', widget: 'string', required: false }
      - { label: 'Redirect to', name: 'redirect_to', widget: 'string', required: false }
        
  - name: 'events'
    label: 'Event'
    folder: '_events/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: 'event/{{filename}}'
    fields:
    - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'event' }
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
    - { label: 'Publish date', hint: 'This should usually be set to today’s date', name: 'date', widget: 'datetime' , date_format: "YYYY-MM-DD", time_format: "HH:mm" }
    - label: 'Event details'
      name: 'event'
      widget: 'object'
      required: true
      fields:
      - { label: 'Event start date and time', name: 'start', widget: 'datetime' , date_format: "YYYY-MM-DD", time_format: "HH:mm", picker_utc: true, required: true }
      - { label: 'Event end date and time', name: 'end', widget: 'datetime' , date_format: "YYYY-MM-DD", time_format: "HH:mm", picker_utc: true, required: false }
      - { label: 'Event registration deadline', name: 'deadline', widget: 'datetime' , date_format: "YYYY-MM-DD", time_format: "HH:mm", picker_utc: true }
      - { label: 'Event host', name: 'host', widget: 'string', required: false, default: 'Civil Service LGBT+ Network' }
      - { label: 'Event location', name: 'location', widget: 'string' }
      - { label: 'Registration site or form URL', name: 'link', widget: 'string', required: false }
      - { label: 'Registration email address', name: 'email', widget: 'string', required: false }
      - { label: 'Alternative registration message', hint: 'For example, if participants don’t need to register in advance, include a message here about what to do like; ”No need to register. Just turn up.”', name: 'no-register', widget: 'string', required: false }
    - { label: 'Category', name: 'category', widget: 'list', required: false }
    - { label: 'Body', name: 'body', widget: 'markdown' }
    - { label: 'Redirect from', name: 'redirect_from', widget: 'string', required: false }
    - { label: 'Redirect to', name: 'redirect_to', widget: 'string', required: false }
      
  - name: 'publications'
    label: 'Publication'
    folder: '_publications/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: 'publication/{{year}}/{{month}}/{{day}}/{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'publication' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Publish date', name: 'date', widget: 'datetime' , date_format: "YYYY-MM-DD", time_format: "HH:mm" }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'list', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Featured image', name: 'image', widget: 'image', choose_url: true, required: false }
      - { label: 'YouTube video URL', name: 'video', widget: 'string', required: false }
      - { label: 'Redirect from', name: 'redirect_from', widget: 'string', required: false }
      - { label: 'Redirect to', name: 'redirect_to', widget: 'string', required: false }
      
  - name: 'consultations'
    label: 'Consultation'
    folder: '_consultations/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: 'consultation/{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'consultation' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Publish date', name: 'date', widget: 'datetime' , date_format: "YYYY-MM-DD", time_format: "HH:mm" }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'list', required: false }
      - { label: 'Consultation link', name: 'link', widget: 'string' }
      - { label: 'Consultation end date', name: 'end-date', widget: 'datetime' , date_format: "YYYY-MM-DD", time_format: "HH:mm" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Redirect from', name: 'redirect_from', widget: 'string', required: false }
      - { label: 'Redirect to', name: 'redirect_to', widget: 'string', required: false }
      
  - name: 'manuals'
    label: 'Volunteer guidance'
    folder: '_manuals/'
    create: true
    slug: "{{slug}}"
    preview_path: 'manual/{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'select', options: ['manual', 'publication'], default: 'manual' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Category', name: 'category', widget: 'list', required: false }
      - { label: 'Show meta info (author, Publish date, etc)', name: 'meta-info', widget: 'select', options: ['true', 'false'], default: 'false' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Redirect from', name: 'redirect_from', widget: 'string', required: false }
      - { label: 'Redirect to', name: 'redirect_to', widget: 'string', required: false }
      
  - name: 'rules'
    label: 'Rules'
    folder: '_rules/'
    create: true
    slug: "{{slug}}"
    preview_path: 'our-rules/{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'select', options: ['publication', 'page'], default: 'publication' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Show meta info (author, Publish date, etc)', name: 'meta-info', widget: 'select', options: ['true', 'false'], default: 'false' }
      - { label: 'Category', name: 'category', widget: 'list', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Featured image', name: 'image', widget: 'image', choose_url: true, required: false }
      - { label: 'YouTube video URL', name: 'video', widget: 'string', required: false }
      - { label: 'Redirect from', name: 'redirect_from', widget: 'string', required: false }
      - { label: 'Redirect to', name: 'redirect_to', widget: 'string', required: false }
      
  - name: 'notices'
    label: 'Data notice'
    folder: '_notices/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: 'notice/{{year}}/{{month}}/{{day}}/{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'notice' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Publish date', name: 'date', widget: 'datetime' , date_format: "YYYY-MM-DD", time_format: "HH:mm" }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Redirect from', name: 'redirect_from', widget: 'string', required: false }
      - { label: 'Redirect to', name: 'redirect_to', widget: 'string', required: false }
      
  - name: 'topics'
    label: 'Topic page'
    folder: '_topics/'
    create: true
    slug: "{{slug}}"
    preview_path: 'topic/{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'topic' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish date', name: 'date', widget: 'datetime' , date_format: "YYYY-MM-DD", time_format: "HH:mm" }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Featured image', name: 'image', widget: 'image', choose_url: true, required: false }
      - { label: 'Background colour', name: 'background', widget: 'select', options: ['white', 'yellow', 'cyan', 'magenta'], default: 'white' }
      - { label: 'Redirect from', name: 'redirect_from', widget: 'string', required: false }
      - { label: 'Redirect to', name: 'redirect_to', widget: 'string', required: false }
          
  - name: 'team'
    label: 'Team member'
    folder: '_team/'
    create: true
    identifier_field: person-name
    slug: "{{slug}}"
    preview_path: '{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'team' }
      - { label: 'Team member name', name: 'person-name', widget: 'string', required: true }
      - { label: 'Team member role', name: 'role', widget: 'select', options: ['chair', 'vice chair', 'project team', 'local organiser'], default: 'chair', required: true }
      - { label: 'Team email', name: 'email', widget: 'string', required: false }
      - { label: 'Team member project', name: 'project', widget: 'string' }
      - { label: 'Team member region', name: 'region', widget: 'select', options: ['East Midlands', 'London', 'North East', 'North West', 'Northern Ireland', 'Scotland', 'South East', 'South West', 'Wales', 'West Midlands', 'Yorkshire and Humber'], required: false }
      - { label: 'Archive this team member?', name: 'archive', widget: 'select', options: ['true', 'false'], default: 'false', required: true }
      - { label: 'Biography', name: 'body', widget: 'markdown', required: true }
      - { label: 'Profile picture', name: 'image', widget: 'image', choose_url: true, required: false }

  - name: 'pages'
    label: 'Page'
    folder: '_pages/'
    create: true
    slug: "{{slug}}"
    preview_path: '{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Redirect from', name: 'redirect_from', widget: 'string', required: false }
      - { label: 'Redirect to', name: 'redirect_to', widget: 'string', required: false }
      
  - name: 'agendas'
    label: 'Conference agenda items'
    folder: '_conference/'
    create: true
    slug: "{{slug}}"
    preview_path: 'agenda/{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'news' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Event', hint: 'i.e. “conference-2022”', name: 'event', widget: 'string', default: 'conference-2022' }
      - { label: 'Agenda section', name: 'section', widget: 'select', options: ['agenda', 'after', 'before', 'during', 'logistics', 'session', 'speaker', 'thanks', 'welcome'], required: true }
      - { label: 'Sequence', hint: 'Manually rank order the items in this section. Enter an integer i.e. ‘1’, ‘42’', name: 'sequence', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
