backend:
  name: 'github'
  repo: 'civilservicelgbt/civilservicelgbt.github.io'
  branch: 'main' # Branch to update
  api_root: 'https://api.github.com'
  site_domain: 'civilservicelgbt.netlify.app'
  base_url: 'https://api.netlify.com'
  auth_endpoint: 'auth'
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "Upload “{{path}}”"
    deleteMedia: "Delete “{{path}}”"
    openAuthoring: "'{{message}}'"

site_url: 'https://www.civilservice.lgbt'
logo_url: 'https://www.civilservice.lgbt/assets/images/site/cms-icon.svg'

publish_mode: editorial_workflow

media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: 'news'
    label: 'News'
    folder: '_news/'
    slug: "/news/{{year}}/{{month}}/{{day}}/{{slug}}"
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'news' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'list', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Featured image', name: 'image', widget: 'image', choose_url: true, required: false }